# test_stubs.py — Tests for cygnet.stubs.generate (the TYPE_CHECKING
# snippet generator).  Uses tests.conftest as the introspection target
# since it already has Account / Event / TaggedAccount / LogEntry
# proxies covering the common shape variations (DBKey, AppKey,
# Column-renamed, etc.).

from __future__ import annotations

from cygnet.stubs import generate


class TestGenerate:
    def test_emits_header_and_imports(self):
        out = generate("tests.conftest")
        assert "Generated by `python -m cygnet.stubs tests.conftest`." in out
        assert "from typing import TYPE_CHECKING" in out
        assert "from cygnet.proxy import ColumnProxy, TableProxy" in out

    def test_emits_shadow_class_per_proxy(self):
        out = generate("tests.conftest")
        # Shadow class names are `_<varname>`; the generic param is the
        # original model class name.
        assert "class _AccountTable(TableProxy[Account]):" in out
        assert "class _EventTable(TableProxy[Event]):" in out
        assert "class _LogTable(TableProxy[LogEntry]):" in out

    def test_emits_typed_field_annotations(self):
        """Each FieldMeta becomes an annotated attribute on the shadow."""
        out = generate("tests.conftest")
        # Account: id (Annotated[int, DBKey] -> int), name: str, email: str
        assert "        id: ColumnProxy[int]" in out
        assert "        name: ColumnProxy[str]" in out
        assert "        email: ColumnProxy[str]" in out

    def test_uses_attr_name_not_column_name(self):
        """For a Column-renamed field, the snippet uses the Python attr
        name (T.tag) — that's what users access in code — and types it
        with the original Python type."""
        out = generate("tests.conftest")
        # TaggedAccount.tag is Annotated[str, Column("tag_name")].
        # The shadow's attribute should still be `tag`, not `tag_name`,
        # because that's what the runtime ColumnProxy attribute is.
        assert "class _TaggedTable(TableProxy[TaggedAccount]):" in out
        assert "        tag: ColumnProxy[str]" in out
        assert "tag_name" not in out  # the DB column name shouldn't leak in

    def test_emits_variable_annotations(self):
        """After the class block, each variable gets a typed annotation
        binding it to its shadow class (so mypy doesn't see Any)."""
        out = generate("tests.conftest")
        assert "    AccountTable: _AccountTable" in out
        assert "    EventTable: _EventTable" in out

    def test_else_branch_reproduces_runtime_construction(self):
        """The else-branch is what runs at runtime; it must reconstruct
        every proxy so the snippet replaces the original lines cleanly."""
        out = generate("tests.conftest")
        assert "else:" in out
        assert "import cygnet" in out
        assert "AccountTable = cygnet.Table(Account)" in out

    def test_no_proxies_in_module_returns_helpful_message(self):
        """An empty module gets a comment explaining what didn't happen."""
        # cygnet.proxy itself has no TableProxy *instances* (just the class).
        out = generate("cygnet.proxy")
        assert "No cygnet.Table proxies found in cygnet.proxy" in out

    def test_snippet_is_syntactically_valid_python(self):
        """compile() round-trip — the generated source must parse, so
        users don't paste a snippet that fails at import time."""
        out = generate("tests.conftest")
        # The snippet uses names (Account, Event, etc.) that aren't in
        # this scope, but compile() only checks syntax, not name
        # resolution.  That's enough to catch indentation / brace /
        # missing-colon bugs in the generator.
        compile(out, "<generated>", "exec")
