# stubs.py — Generate TYPE_CHECKING blocks for IDE / mypy autocompletion.
#
# Cygnet's runtime puts ColumnProxy attributes on TableProxy instances
# via setattr.  At type-check time, mypy sees them as Any, so `T.name`
# doesn't autocomplete and a typo like `T.nmae` doesn't error.  The
# real fix would be a mypy plugin (SQLAlchemy 2's path); short of
# that, this module emits a hand-pasteable TYPE_CHECKING block that
# declares each TableProxy variable with a typed shadow class.
#
# Usage:
#     python -m cygnet.stubs myapp.models
#
# The output is a self-contained snippet to paste into the same
# module; runtime behaviour is unchanged because the snippet's
# `if TYPE_CHECKING:` branch is invisible at import time, and the
# `else:` branch reproduces the original `XTable = cygnet.Table(X)`
# lines so the snippet is the *only* place the proxies are
# constructed (no risk of double-construction).
#
# Regeneration is *manual*: there is no import-time hook and no
# watch mode.  The user runs `python -m cygnet.stubs ...` after
# changing models and pastes the result back into the module.  That
# trade-off is intentional — a runtime auto-stub would add import
# cost and a hidden codegen step, which conflicts with Cygnet's
# "models are plain dataclasses" promise.

from __future__ import annotations

import argparse
import importlib
import sys
from typing import Any

from .proxy import TableProxy


def generate(module_path: str) -> str:
    """Build a TYPE_CHECKING snippet for every TableProxy in a module.

    Imports `module_path` at runtime, scans its namespace for
    TableProxy instances, and emits Python source that — when pasted
    into the user's models module — gives mypy / IDEs typed views of
    each proxy.

    The generated snippet is purely additive at type-check time and
    fully replaces the original `XTable = cygnet.Table(X)` lines at
    runtime (the snippet's else-branch reconstructs them).
    """
    module = importlib.import_module(module_path)
    # Preserve declaration order from the module's namespace; for
    # 3.7+ Python this matches the source order.
    #
    # We collect by isinstance(TableProxy) rather than by scanning
    # dataclasses + @cygnet.table: a user might have model classes
    # defined elsewhere and only construct the proxies here, and
    # conversely they might define a class with DBKey but never
    # build a proxy for it.  The proxy variables are what mypy
    # actually sees, so they are what we emit stubs for.
    proxies: list[tuple[str, Any]] = [
        (name, value)
        for name, value in vars(module).items()
        if isinstance(value, TableProxy)
    ]
    if not proxies:
        return f"# No cygnet.Table proxies found in {module_path}.\n"

    lines = [
        f"# Generated by `python -m cygnet.stubs {module_path}`.",
        "# Paste into the module that defines your TableProxy variables,",
        "# replacing the original `XTable = cygnet.Table(Xclass)` lines.",
        "# Regenerate after model changes.",
        "",
        "from typing import TYPE_CHECKING",
        "",
        "if TYPE_CHECKING:",
        "    from cygnet.proxy import ColumnProxy, TableProxy",
        "",
    ]

    # Shadow class per proxy.  Names are `_<varname>` so mypy can match
    # them to the user-facing variable name.  The class extends
    # TableProxy[ModelClass] so generic-aware APIs (cygnet.get,
    # cygnet.save) keep working with the same return types.
    for name, proxy in proxies:
        cls = proxy._meta.cls
        shadow_name = f"_{name}"
        lines.append(f"    class {shadow_name}(TableProxy[{cls.__name__}]):")
        # f.attr_name is the Python identifier, NOT f.column_name.
        # `Column("renamed")` overrides the SQL name but leaves the
        # attribute alone, and IDE autocomplete is about the Python
        # attribute the user actually types (T.col_attr), so the SQL
        # rename is irrelevant for stub purposes.
        #
        # f.python_type is already the Annotated-stripped underlying
        # type from meta.py — DBKey / AppKey / ForeignKey markers are
        # gone by the time we see the field, so a FK like
        # `Annotated[int, ForeignKey(Parent)]` correctly renders as
        # `ColumnProxy[int]` rather than leaking metadata.
        #
        # Frozen-dataclass + DBKey is rejected at TableMeta construction
        # time, so by the time a TableProxy exists, the field list is
        # already guaranteed safe — no need to filter here.
        for f in proxy._meta.fields:
            ft_str = _format_type(f.python_type)
            lines.append(f"        {f.attr_name}: ColumnProxy[{ft_str}]")
        lines.append("")

    # Variable annotations: tells mypy the proxy variable is the
    # shadow type, not the bare TableProxy that cygnet.Table() returns.
    for name, _ in proxies:
        lines.append(f"    {name}: _{name}")

    # Else-branch: actual runtime construction.  Identical to what the
    # user originally had; the snippet replaces those lines so the proxy
    # is constructed exactly once.
    lines.append("else:")
    lines.append("    import cygnet")
    for name, proxy in proxies:
        cls = proxy._meta.cls
        lines.append(f"    {name} = cygnet.Table({cls.__name__})")
    lines.append("")

    return "\n".join(lines)


def _format_type(t: Any) -> str:
    """Render a Python type in stub-friendly form.

    Plain classes use __name__ (`int`, `str`, `MyClass`); union /
    parameterised generic types fall through to str() which gives
    `int | None`, `list[str]`, etc.
    """
    name: Any = getattr(t, "__name__", None)
    if isinstance(name, str):
        return name
    return str(t)


def _main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m cygnet.stubs",
        description=(
            "Generate a TYPE_CHECKING block giving IDE autocompletion "
            "for cygnet.Table proxies in a module."
        ),
    )
    parser.add_argument(
        "module",
        help="Importable module path, e.g. myapp.models",
    )
    args = parser.parse_args(argv)

    # Add the current directory to sys.path so users can run this from
    # their project root without setting PYTHONPATH manually.
    if "" not in sys.path:
        sys.path.insert(0, "")

    snippet = generate(args.module)
    print(snippet)
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
